export interface MenuItem {
  id: string;
  name: string;
  nameAr: string;
  description: string;
  descriptionAr: string;
  price: number;
  image: string;
  category: string;
  rating: number;
  orderCount: number;
  preparationTime: number;
  isAvailable: boolean;
  isRecommended?: boolean;
  discount?: number;
}

export const categories = [
  { id: 'meals', name: 'Meals', nameAr: 'وجبات', icon: '🍽️' },
  { id: 'drinks', name: 'Drinks', nameAr: 'مشروبات', icon: '🥤' },
  { id: 'desserts', name: 'Desserts', nameAr: 'حلويات', icon: '🍰' },
  { id: 'sandwiches', name: 'Sandwiches', nameAr: 'سندويشات', icon: '🥪' },
  { id: 'coffee', name: 'Coffee', nameAr: 'قهوة', icon: '☕' },
  { id: 'breakfast', name: 'Breakfast', nameAr: 'فطور', icon: '🍳' },
];

export const menuItems: MenuItem[] = [
  // Meals
  {
    id: '1',
    name: 'Grilled Chicken',
    nameAr: 'دجاج مشوي',
    description: 'Perfectly grilled chicken with special herbs',
    descriptionAr: 'دجاج مشوي مع أعشاب خاصة',
    price: 45.99,
    image: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=500',
    category: 'meals',
    rating: 4.8,
    orderCount: 1250,
    preparationTime: 25,
    isAvailable: true,
    isRecommended: true,
  },
  {
    id: '2',
    name: 'Beef Burger',
    nameAr: 'برجر لحم',
    description: 'Juicy beef burger with fresh vegetables',
    descriptionAr: 'برجر لحم طري مع خضروات طازجة',
    price: 38.99,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
    category: 'meals',
    rating: 4.7,
    orderCount: 980,
    preparationTime: 20,
    isAvailable: true,
    discount: 15,
  },
  {
    id: '3',
    name: 'Pasta Alfredo',
    nameAr: 'باستا الفريدو',
    description: 'Creamy pasta with parmesan cheese',
    descriptionAr: 'باستا كريمية مع جبن البارميزان',
    price: 42.99,
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500',
    category: 'meals',
    rating: 4.6,
    orderCount: 750,
    preparationTime: 18,
    isAvailable: true,
  },
  {
    id: '4',
    name: 'Grilled Salmon',
    nameAr: 'سلمون مشوي',
    description: 'Fresh salmon with lemon butter sauce',
    descriptionAr: 'سلمون طازج مع صلصة الليمون والزبدة',
    price: 58.99,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500',
    category: 'meals',
    rating: 4.9,
    orderCount: 650,
    preparationTime: 22,
    isAvailable: true,
    isRecommended: true,
  },

  // Drinks
  {
    id: '5',
    name: 'Fresh Orange Juice',
    nameAr: 'عصير برتقال طازج',
    description: 'Freshly squeezed orange juice',
    descriptionAr: 'عصير برتقال طازج معصور',
    price: 15.99,
    image: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=500',
    category: 'drinks',
    rating: 4.5,
    orderCount: 1500,
    preparationTime: 5,
    isAvailable: true,
  },
  {
    id: '6',
    name: 'Mango Smoothie',
    nameAr: 'سموذي مانجو',
    description: 'Refreshing mango smoothie',
    descriptionAr: 'سموذي مانجو منعش',
    price: 18.99,
    image: 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=500',
    category: 'drinks',
    rating: 4.7,
    orderCount: 890,
    preparationTime: 5,
    isAvailable: true,
    isRecommended: true,
  },
  {
    id: '7',
    name: 'Iced Lemonade',
    nameAr: 'ليموناضة مثلجة',
    description: 'Cool lemonade with mint',
    descriptionAr: 'ليموناضة باردة مع النعناع',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1523677011781-c91d1bbe2f0f?w=500',
    category: 'drinks',
    rating: 4.4,
    orderCount: 720,
    preparationTime: 3,
    isAvailable: true,
  },

  // Desserts
  {
    id: '8',
    name: 'Chocolate Cake',
    nameAr: 'كيك شوكولاتة',
    description: 'Rich chocolate cake with ganache',
    descriptionAr: 'كيك شوكولاتة غني مع الجاناش',
    price: 28.99,
    image: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500',
    category: 'desserts',
    rating: 4.9,
    orderCount: 1100,
    preparationTime: 10,
    isAvailable: true,
    discount: 10,
  },
  {
    id: '9',
    name: 'Tiramisu',
    nameAr: 'تيراميسو',
    description: 'Classic Italian dessert',
    descriptionAr: 'حلوى إيطالية كلاسيكية',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500',
    category: 'desserts',
    rating: 4.8,
    orderCount: 850,
    preparationTime: 8,
    isAvailable: true,
    isRecommended: true,
  },
  {
    id: '10',
    name: 'Cheesecake',
    nameAr: 'تشيز كيك',
    description: 'Creamy New York style cheesecake',
    descriptionAr: 'تشيز كيك كريمي على طريقة نيويورك',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1533134242820-b0a0c9ce1bb4?w=500',
    category: 'desserts',
    rating: 4.7,
    orderCount: 920,
    preparationTime: 10,
    isAvailable: true,
  },

  // Sandwiches
  {
    id: '11',
    name: 'Club Sandwich',
    nameAr: 'كلوب ساندويش',
    description: 'Triple-decker with chicken and bacon',
    descriptionAr: 'ساندويش ثلاثي الطبقات مع الدجاج',
    price: 35.99,
    image: 'https://images.unsplash.com/photo-1567234669003-dce7a7a88821?w=500',
    category: 'sandwiches',
    rating: 4.6,
    orderCount: 780,
    preparationTime: 15,
    isAvailable: true,
  },
  {
    id: '12',
    name: 'Falafel Wrap',
    nameAr: 'لفة فلافل',
    description: 'Crispy falafel with tahini sauce',
    descriptionAr: 'فلافل مقرمشة مع صلصة الطحينة',
    price: 24.99,
    image: 'https://images.unsplash.com/photo-1592415499556-fece0c9808e9?w=500',
    category: 'sandwiches',
    rating: 4.5,
    orderCount: 890,
    preparationTime: 12,
    isAvailable: true,
    isRecommended: true,
  },

  // Coffee
  {
    id: '13',
    name: 'Cappuccino',
    nameAr: 'كابتشينو',
    description: 'Classic Italian cappuccino',
    descriptionAr: 'كابتشينو إيطالي كلاسيكي',
    price: 16.99,
    image: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=500',
    category: 'coffee',
    rating: 4.8,
    orderCount: 1800,
    preparationTime: 5,
    isAvailable: true,
  },
  {
    id: '14',
    name: 'Caramel Latte',
    nameAr: 'لاتيه كراميل',
    description: 'Sweet caramel flavored latte',
    descriptionAr: 'لاتيه بنكهة الكراميل الحلوة',
    price: 19.99,
    image: 'https://images.unsplash.com/photo-1599639957043-f3aa5c986398?w=500',
    category: 'coffee',
    rating: 4.7,
    orderCount: 1350,
    preparationTime: 6,
    isAvailable: true,
    isRecommended: true,
  },
  {
    id: '15',
    name: 'Espresso',
    nameAr: 'إسبريسو',
    description: 'Strong Italian espresso',
    descriptionAr: 'إسبريسو إيطالي قوي',
    price: 12.99,
    image: 'https://images.unsplash.com/photo-1579992357154-faf4bde95b3d?w=500',
    category: 'coffee',
    rating: 4.6,
    orderCount: 980,
    preparationTime: 3,
    isAvailable: true,
  },

  // Breakfast
  {
    id: '16',
    name: 'English Breakfast',
    nameAr: 'فطور إنجليزي',
    description: 'Full English breakfast platter',
    descriptionAr: 'طبق فطور إنجليزي كامل',
    price: 48.99,
    image: 'https://images.unsplash.com/photo-1533089860892-a7c6f0a88666?w=500',
    category: 'breakfast',
    rating: 4.8,
    orderCount: 650,
    preparationTime: 20,
    isAvailable: true,
  },
  {
    id: '17',
    name: 'Pancakes',
    nameAr: 'بان كيك',
    description: 'Fluffy pancakes with maple syrup',
    descriptionAr: 'بان كيك طري مع شراب القيقب',
    price: 32.99,
    image: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500',
    category: 'breakfast',
    rating: 4.9,
    orderCount: 1450,
    preparationTime: 15,
    isAvailable: true,
    isRecommended: true,
  },
  {
    id: '18',
    name: 'Avocado Toast',
    nameAr: 'توست أفوكادو',
    description: 'Sourdough toast with mashed avocado',
    descriptionAr: 'توست مع أفوكادو مهروس',
    price: 29.99,
    image: 'https://images.unsplash.com/photo-1588137378633-dea1336ce1e2?w=500',
    category: 'breakfast',
    rating: 4.6,
    orderCount: 780,
    preparationTime: 10,
    isAvailable: true,
  },
];

export const offers = [
  {
    id: 'offer1',
    title: 'Buy 2 Get 1 Free',
    titleAr: 'اشتري 2 واحصل على 1 مجاناً',
    description: 'On all desserts',
    descriptionAr: 'على جميع الحلويات',
    discount: 33,
    validUntil: '2025-12-31',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500',
  },
  {
    id: 'offer2',
    title: '20% Off',
    titleAr: 'خصم 20%',
    description: 'On orders above 100 SAR',
    descriptionAr: 'على الطلبات فوق 100 ريال',
    discount: 20,
    validUntil: '2025-12-31',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=500',
  },
];
